-- Business reference data (free, starter, pro) is installed by
-- 20260915162000_seed_business_plans.sql on every environment.
-- Synthetic users, events and orders belong to a separate staging-only seed.
