-- Reconcile grants observed in production on 2026-09-15.
-- The historical migrations replayed with broader privileges than production.
-- Does not change function bodies or customer data.

REVOKE ALL ON FUNCTION "public"."admin_update_order_attendee"("p_attendee_id" "uuid", "p_attendee" "jsonb") FROM "anon";
REVOKE ALL ON FUNCTION "public"."apply_subscription_state"("p_org_id" "uuid", "p_provider" "text", "p_customer_id" "text", "p_subscription_id" "text", "p_status" "text", "p_current_period_end" timestamp with time zone, "p_raw" "jsonb") FROM "anon";
REVOKE ALL ON FUNCTION "public"."apply_subscription_state"("p_org_id" "uuid", "p_provider" "text", "p_customer_id" "text", "p_subscription_id" "text", "p_status" "text", "p_current_period_end" timestamp with time zone, "p_raw" "jsonb") FROM "authenticated";
REVOKE ALL ON FUNCTION "public"."create_mollie_connect_state"("p_org_id" "uuid", "p_mode" "text", "p_return_base_url" "text") FROM "anon";
REVOKE ALL ON FUNCTION "public"."create_subscription_intent"("p_org_id" "uuid", "p_plan" "text") FROM "anon";
REVOKE ALL ON FUNCTION "public"."expire_orders"("p_limit" integer) FROM "anon";
REVOKE ALL ON FUNCTION "public"."expire_orders"("p_limit" integer) FROM "authenticated";
REVOKE ALL ON FUNCTION "public"."get_dashboard_bootstrap"() FROM "anon";
REVOKE ALL ON FUNCTION "public"."get_event_by_slug"("p_org_id" "uuid", "p_event_slug" "text") FROM "anon";
REVOKE ALL ON FUNCTION "public"."get_event_registrations_count"("p_event_id" "uuid") FROM "anon";
REVOKE ALL ON FUNCTION "public"."get_event_registrations_count"("p_event_id" "uuid") FROM "authenticated";
REVOKE ALL ON FUNCTION "public"."get_events_overview"("p_org_id" "uuid") FROM "anon";
REVOKE ALL ON FUNCTION "public"."get_org_mollie_connect_secrets"("p_org_id" "uuid") FROM "anon";
REVOKE ALL ON FUNCTION "public"."get_org_mollie_connect_secrets"("p_org_id" "uuid") FROM "authenticated";
REVOKE ALL ON FUNCTION "public"."get_org_plan"("p_org_id" "uuid") FROM "anon";
REVOKE ALL ON FUNCTION "public"."get_org_plan"("p_org_id" "uuid") FROM "authenticated";
REVOKE ALL ON FUNCTION "public"."is_attendee_org_member"("p_attendee_id" "uuid") FROM "anon";
REVOKE ALL ON FUNCTION "public"."is_attendee_org_member"("p_attendee_id" "uuid") FROM "authenticated";
REVOKE ALL ON FUNCTION "public"."is_event_org_member"("p_event_id" "uuid") FROM "anon";
REVOKE ALL ON FUNCTION "public"."is_event_paid"("p_event_id" "uuid") FROM "anon";
REVOKE ALL ON FUNCTION "public"."is_event_paid"("p_event_id" "uuid") FROM "authenticated";
REVOKE ALL ON FUNCTION "public"."issue_order_tickets"("p_order_id" "uuid") FROM "anon";
REVOKE ALL ON FUNCTION "public"."issue_order_tickets"("p_order_id" "uuid") FROM "authenticated";
REVOKE ALL ON FUNCTION "public"."rpc_create_invoice_from_mollie_payment"("p_input" "jsonb") FROM "anon";
REVOKE ALL ON FUNCTION "public"."rpc_create_invoice_from_mollie_payment"("p_input" "jsonb") FROM "authenticated";
REVOKE ALL ON FUNCTION "public"."rpc_set_invoice_pdf_path"("p_invoice_id" "uuid", "p_pdf_path" "text") FROM "anon";
REVOKE ALL ON FUNCTION "public"."rpc_set_invoice_pdf_path"("p_invoice_id" "uuid", "p_pdf_path" "text") FROM "authenticated";
REVOKE ALL ON FUNCTION "public"."search_event_admin_orders_view"("p_org_id" "uuid", "p_event_slug" "text", "p_event_id" "uuid", "p_query" "text", "p_filter_mode" "text", "p_orders_limit" integer, "p_orders_offset" integer) FROM "anon";
REVOKE ALL ON FUNCTION "public"."search_event_admin_tickets_view"("p_event_id" "uuid", "p_query" "text", "p_limit" integer, "p_offset" integer) FROM "anon";
REVOKE ALL ON FUNCTION "public"."slugify"("input" "text") FROM "anon";
REVOKE ALL ON FUNCTION "public"."slugify"("input" "text") FROM "authenticated";
REVOKE ALL ON FUNCTION "public"."update_org_mollie_tokens"("p_org_id" "uuid", "p_access_token_enc" "text", "p_refresh_token_enc" "text", "p_enc_kid" "text", "p_enc_alg" "text", "p_expires_at" timestamp with time zone, "p_scopes" "text") FROM "anon";
REVOKE ALL ON FUNCTION "public"."update_org_mollie_tokens"("p_org_id" "uuid", "p_access_token_enc" "text", "p_refresh_token_enc" "text", "p_enc_kid" "text", "p_enc_alg" "text", "p_expires_at" timestamp with time zone, "p_scopes" "text") FROM "authenticated";
REVOKE ALL ON FUNCTION "public"."upsert_organization_mollie_connect"("p_input" "jsonb") FROM "anon";
REVOKE ALL ON FUNCTION "public"."upsert_organization_mollie_connect"("p_input" "jsonb") FROM "authenticated";
REVOKE MAINTAIN ON TABLE "public"."invoice_peppol" FROM "anon";
REVOKE MAINTAIN ON TABLE "public"."invoice_peppol" FROM "authenticated";

REVOKE ALL ON FUNCTION "private"."assert_rate_limit"("p_key" "text", "p_limit" integer, "p_window_seconds" integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION "private"."can_create_event"("p_org_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "private"."generate_unique_org_slug"("base_name" "text") FROM PUBLIC;
GRANT ALL ON FUNCTION "private"."generate_unique_org_slug"("base_name" "text") TO "anon";
GRANT ALL ON FUNCTION "private"."generate_unique_org_slug"("base_name" "text") TO "authenticated";
GRANT ALL ON FUNCTION "private"."generate_unique_org_slug"("base_name" "text") TO "service_role";
REVOKE ALL ON FUNCTION "private"."prune_rate_limits"("p_older_than" interval) FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."admin_delete_order"("p_order_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."admin_grant_subscription"("p_org" "uuid", "p_plan" "text", "p_days" integer, "p_period_end" timestamp with time zone) FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."admin_update_order_attendee"("p_attendee_id" "uuid", "p_attendee" "jsonb") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."apply_subscription_state"("p_org_id" "uuid", "p_provider" "text", "p_customer_id" "text", "p_subscription_id" "text", "p_status" "text", "p_current_period_end" timestamp with time zone, "p_raw" "jsonb") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."assert_can_add_form_field"("p_org_id" "uuid", "p_event_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."assert_can_add_product"("p_org_id" "uuid", "p_event_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."assert_can_create_paid_product"("p_org_id" "uuid", "p_event_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."assert_event_registrations_limit_bulk"("p_org_id" "uuid", "p_event_id" "uuid", "p_new_attendees" integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."assert_rate_limit"("p_key" "text", "p_limit" integer, "p_window_seconds" integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."can_create_paid_product"("p_org_id" "uuid", "p_event_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."check_in_ticket_internal"("p_ticket_id" "uuid", "p_event_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."claim_order_confirmation_email"("p_order_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."create_mollie_connect_state"("p_org_id" "uuid", "p_mode" "text", "p_return_base_url" "text") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."create_subscription_intent"("p_org_id" "uuid", "p_plan" "text") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."expire_orders"("p_limit" integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."get_dashboard_bootstrap"() FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."get_event_by_slug"("p_org_id" "uuid", "p_event_slug" "text") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."get_event_registrations_count"("p_event_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."get_event_tickets_admin"("p_event_id" "uuid", "p_limit" integer, "p_offset" integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."get_events_overview"("p_org_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."get_org_mollie_connect_secrets"("p_org_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."get_org_plan"("p_org_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."get_plan_limits"("p_plan" "text") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."get_public_org_by_slug"("p_slug" "text") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."is_attendee_org_member"("p_attendee_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."is_event_org_member"("p_event_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."is_event_paid"("p_event_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."is_order_org_member"("p_order_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."is_org_member"("p_org_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."issue_order_tickets"("p_order_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."log_email_once"("p_order_id" "uuid", "p_kind" "text") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."mark_order_confirmation_email_error"("p_order_id" "uuid", "p_error" "text") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."mark_order_confirmation_email_sent"("p_order_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."rpc_create_invoice_from_mollie_payment"("p_input" "jsonb") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."rpc_create_invoice_peppol"("p_input" "jsonb") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."rpc_get_organization_billing"("p_org_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."rpc_list_invoices"("p_org_id" "uuid", "p_limit" integer, "p_cursor_issued_at" timestamp with time zone, "p_cursor_id" "uuid") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."rpc_set_invoice_pdf_path"("p_invoice_id" "uuid", "p_pdf_path" "text") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."rpc_update_invoice_peppol_status"("p_input" "jsonb") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."rpc_upsert_organization_billing"("p_input" "jsonb") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."search_event_admin_orders_view"("p_org_id" "uuid", "p_event_slug" "text", "p_event_id" "uuid", "p_query" "text", "p_filter_mode" "text", "p_orders_limit" integer, "p_orders_offset" integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."search_event_admin_tickets_view"("p_event_id" "uuid", "p_query" "text", "p_limit" integer, "p_offset" integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."slugify"("input" "text") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."update_org_mollie_tokens"("p_org_id" "uuid", "p_access_token_enc" "text", "p_refresh_token_enc" "text", "p_enc_kid" "text", "p_enc_alg" "text", "p_expires_at" timestamp with time zone, "p_scopes" "text") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."upsert_organization_mollie_connect"("p_input" "jsonb") FROM PUBLIC;
